POST http://localhost:3003/api/ais
Content-Type: application/json

{
    "ai_name": "AI Model Amy",
    "ai_star_rating": 5,
    "ai_description": "AI model for stdy",
    "ai_saves": 100,
    "ai_price": "$50",
    "ai_categories": ["Machine Learning"],
    "ai_timecreated": "2023-08-05T00:00:00.000Z",
    "ai_sold": 0,
    "ai_seller_id": "64cf68540b792b2e8739390c"
}
####
POST http://localhost:3003/api/reviews
Content-Type: application/json

{
    "review_ai_id": "64cf6aa9ccd6062e6f909700",
    "review_reviewer_id": "64ceb53dfc3940a3d389b73a",
    "review_star": 4,
    "review_content": "This AI model is amazing!",
    "review_time": "2023-08-05T12:00:00Z",
    "review_like": 10,
    "review_dislike": 2
}

####
POST http://localhost:3003/api/sellers
Content-Type: application/json

{
    "seller_storeName": "Tech Store 1",
    "seller_phoneNumber": "123-456-7890",
    "seller_Address": "123 Main Street, City, Country",
    "seller_user_id": "64ceb53dfc3940a3d389b739",
    "seller_list_ai_id": [],
    "seller_sold_ai_id": []
}

####
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "user_name": "john_doe",
  "user_password": "password123",
  "user_firstname": "John",
  "user_lastname": "Doe",
  "user_email": "john.doe@example.com",
  "user_seller_id": "64cf9b56e42f2a127709767e"
}

####
POST http://localhost:3003/api/news
Content-Type: application/json

{
  "new_title": "New Title",
  "new_content": "New Content",
  "new_likes": 10,
  "new_dislikes": 2,
  "new_date": "2023-08-05"
}

